AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 300

Metrics/MethodLength:
  Max: 25

Metrics/ParameterLists:
  Max: 8

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: true

Metrics/PerceivedComplexity:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/AndOr:
  Enabled: false

Style/Not:
  Enabled: false

Style/FileName:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Documentation:
  Enabled: false

Style/CaseIndentation:
  IndentWhenRelativeTo: case
  SupportedStyles:
    - case
    - end
  IndentOneStep: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '[]'
    '%W': '[]'

Style/AccessModifierIndentation:
  EnforcedStyle: indent

Style/SignalException:
  Enabled: false

Style/IndentationWidth:
  Enabled: false

Lint/EndAlignment:
  AlignWith: variable

Lint/DefEndAlignment:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false
